# Vapor starter

Vapor starter is starter kit for react & redux

### Prerequisites

You need to install requirement :

```
* Node : v8.10.0
* NPM : v6.0.1
```

### Installing

Step by Step

```
npm install
```

## Running

```
npm start
```

## Authors

* **Bhumyamka Yala**  - [Github](https://github.com/bhumyamka)

## License

This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details
